using System.Text.Json;

namespace PiuScoresWatcher.Core.Recognition;

/// <summary>What a grade badge looked like: the closest of the nine RISE grades, how close, and by how much it beat the next.</summary>
[ExcludeFromCodeCoverage]
public readonly record struct GradeMatch(string? Grade, double Similarity, double Margin)
{
    /// <summary>The weakest a correct match has been on the fixture screens (0.77, mid-fade) and the thinnest lead (0.11), with room.</summary>
    public bool IsConfident => Grade is not null && Similarity >= 0.7 && Margin >= 0.05;
}

/// <summary>
///     The Warm Up song list's grade badge, told apart by comparing it with the game's nine RISE grade
///     sprites (D47): the badge's bounding box averaged into 16x16 cells of colour, centred and scaled to
///     unit length, against the same of each sprite composited over the panel. The features are
///     generated by <c>tools/reader-lab/songlist.py</c> into <c>grades.json</c>; this bins exactly as it does.
/// </summary>
public sealed class GradeBadges
{
    private static readonly Lazy<GradeBadges> EmbeddedSet = new(LoadEmbedded);
    private readonly (byte R, byte G, byte B) _background;
    private readonly Dictionary<string, double[]> _grades;
    private readonly int _size;

    private GradeBadges(int size, (byte, byte, byte) background, Dictionary<string, double[]> grades)
    {
        _size = size;
        _background = background;
        _grades = grades;
    }

    public static GradeBadges Embedded => EmbeddedSet.Value;

    public GradeMatch Classify(ScreenImage image, PixelRect region)
    {
        var feature = Feature(image, region);
        if (feature is null)
            return new GradeMatch(null, 0, 0);
        string? best = null;
        double first = double.MinValue, second = double.MinValue;
        foreach (var (grade, template) in _grades)
        {
            var similarity = 0.0;
            for (var i = 0; i < feature.Length; i++)
                similarity += feature[i] * template[i];
            if (similarity > first)
            {
                second = first;
                first = similarity;
                best = grade;
            }
            else if (similarity > second)
            {
                second = similarity;
            }
        }

        return new GradeMatch(best, first, first - second);
    }

    /// <summary>The badge is whatever differs from the panel behind it; its box is binned into <c>size</c> x <c>size</c> cells of mean colour.</summary>
    private double[]? Feature(ScreenImage image, PixelRect region)
    {
        int x0 = int.MaxValue, y0 = int.MaxValue, x1 = int.MinValue, y1 = int.MinValue;
        for (var y = region.Y0; y < region.Y1; y++)
        for (var x = region.X0; x < region.X1; x++)
        {
            var difference = Math.Abs(image.Red(x, y) - _background.R) + Math.Abs(image.Green(x, y) - _background.G)
                                                                        + Math.Abs(image.Blue(x, y) - _background.B);
            if (difference <= 60)
                continue;
            x0 = Math.Min(x0, x);
            y0 = Math.Min(y0, y);
            x1 = Math.Max(x1, x + 1);
            y1 = Math.Max(y1, y + 1);
        }

        if (x1 <= x0 || y1 <= y0)
            return null;

        var width = x1 - x0;
        var height = y1 - y0;
        var feature = new double[_size * _size * 3];
        var i = 0;
        for (var cy = 0; cy < _size; cy++)
        {
            var ya = y0 + cy * height / _size;
            var yb = Math.Max(ya + 1, y0 + (cy + 1) * height / _size);
            for (var cx = 0; cx < _size; cx++)
            {
                var xa = x0 + cx * width / _size;
                var xb = Math.Max(xa + 1, x0 + (cx + 1) * width / _size);
                double r = 0, g = 0, b = 0;
                var count = 0;
                for (var y = ya; y < yb; y++)
                for (var x = xa; x < xb; x++)
                {
                    r += image.Red(x, y);
                    g += image.Green(x, y);
                    b += image.Blue(x, y);
                    count++;
                }

                feature[i++] = r / count;
                feature[i++] = g / count;
                feature[i++] = b / count;
            }
        }

        var mean = feature.Average();
        var norm = 0.0;
        for (var k = 0; k < feature.Length; k++)
        {
            feature[k] -= mean;
            norm += feature[k] * feature[k];
        }

        norm = Math.Sqrt(norm) + 1e-9;
        for (var k = 0; k < feature.Length; k++)
            feature[k] /= norm;
        return feature;
    }

    internal static GradeBadges Parse(Stream json)
    {
        using var document = JsonDocument.Parse(json);
        var root = document.RootElement;
        var size = root.GetProperty("size").GetInt32();
        var background = root.GetProperty("background").EnumerateArray().Select(c => (byte)c.GetInt32()).ToArray();
        var grades = new Dictionary<string, double[]>(StringComparer.Ordinal);
        foreach (var grade in root.GetProperty("grades").EnumerateObject())
        {
            var values = grade.Value.EnumerateArray().Select(v => v.GetDouble()).ToArray();
            if (values.Length != size * size * 3)
                throw new InvalidDataException($"Grade {grade.Name} has {values.Length} values, not {size * size * 3}.");
            grades[grade.Name] = values;
        }

        return new GradeBadges(size, (background[0], background[1], background[2]), grades);
    }

    private static GradeBadges LoadEmbedded()
    {
        using var stream = typeof(GradeBadges).Assembly.GetManifestResourceStream("grades.json")
                           ?? throw new InvalidOperationException("grades.json is not embedded in Core.");
        return Parse(stream);
    }
}
